### ISSUE TITLE
The visual result is abnormal？

### ISSUE THREAD

**Issue by kt-rax** [hku-mars/livox_camera_calib#80]
I have follow the steps and up to the roslaunch.

But seems got no result.Is there anybody could give some suggestions or comments.Thanks!

roslaunch livox_camera_calib calib.launch

![image](https://user-images.githubusercontent.com/18671477/222661183-6fde56df-f646-40ef-acdd-546091aee1eb.png)

**Comment by kt-rax** [comment]
![image](https://user-images.githubusercontent.com/18671477/222667108-92b6a3be-e15d-443e-ac2c-a82a8e3cfe53.png)

**Comment by Yangbit666** [comment]
前辈你好，想请问您编译报错的问题解决了吗？

**Comment by Yangbit666** [comment]
> 

Maybe I need to use lower version Ceres Soler,  as other poster metioned.

**Comment by Snowbound9173** [comment]
Looks like you didn't correctly configure the paths required. You can even see the message "Failed to open settings for file at: ...."

You will need to go into  the calib.yaml file and update your paths. I realise this is super old but if someone stumbles across it it might help.

```
# Data path. adjust them!
common:
    image_file: "/home/livox/ws_livox_camera_calib/data/image/0.png"
    pcd_file: "/home/livox/ws_livox_camera_calib/data/pcd/0.pcd"
    result_file: "/home/livox/ws_livox_camera_calib/data/output/extrinsic.txt"

# Camera Parameters. Adjust them!
```
